name: CI 

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  strimzi-kafka-bridge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: "strimzi/strimzi-kafka-bridge"
          ref: eaf86fbe460226c311a403816eaea86c03a2355f
      - name: Java tests
        uses: marcellocordeiro/stress-action@main
        with:
          test_type: maven
          no_stress_runs: 1
          stress_runs: 0
  ripme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          repository: "RipMeApp/ripme"
          ref: 19ea20dcd62d6ea1197073ce9a7236c5c1f47556
      - name: Java tests
        uses: marcellocordeiro/stress-action@main
        with:
          test_type: maven
          no_stress_runs: 1
          stress_runs: 0
